### ISSUE TITLE
Cannot install Exoscale provider version 0.61.0

### ISSUE THREAD

**Issue by lucj** [pulumiverse/pulumi-exoscale#465]
Hi,
the latest v0.61.0 of the Exoscale provider cannot be installed as it seems the assets only contains the source code:

```
$ pulumi preview
...
warning: error downloading provider: plugin asset 'pulumi-resource-exoscale-v0.61.0-darwin-arm64.tar.gz' not found
```

**Comment by rsimonetta-significo** [comment]
For context: I noticed with version 0.59.2 of the Python package, I couldn't create or delete compute instances (likely due to API changes), but version 0.61.0 works as expected.

As a workaround, I manually built and installed the package locally using the Makefile. This gets things working but obviously isn't a sustainable solution in the long term.

Would be great to get the plugin deployment fixed so it can be installed directly via pulumi plugin install without having to build from source.

**Comment by dirien** [comment]
@rsimonetta-significo let me have look. Can you not update to the latest version?

**Comment by lucj** [comment]
Hi @dirien, any news on that one?

**Comment by dirien** [comment]
Hey @lucj and @rsimonetta-significo,

Sorry took a little bit of time and some tech issues on my side forced me to make some more releases until it worked. Please use version `v0.62.7` which is actually the TF version `v0.62.3` of the Exxoscale provider!

**Comment by lucj** [comment]
Thanks @dirien 👍
